### ISSUE TITLE
cant bootstrap

### ISSUE THREAD

**Issue by jonasman** [CocoaPods/Rainforest#67]
```
$ rake bootstrap --trace
rake aborted!
undefined method `scope' for #<Rake::NameSpace:0x007fc82d885e58>
/Users/joao/DEV/Rainforest/Rakefile:1130:in `block (2 levels) in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task_manager.rb:207:in `in_namespace'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/dsl_definition.rb:105:in `namespace'
/Users/joao/DEV/Rainforest/Rakefile:1119:in `block in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/task_manager.rb:207:in `in_namespace'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/dsl_definition.rb:105:in `namespace'
/Users/joao/DEV/Rainforest/Rakefile:1103:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:604:in `raw_load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:89:in `block in load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:88:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:72:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'
```

**Comment by orta** [comment]
Hrm, want to see if you can update your local version of rake? `sudo gem install rake` - I wonder if we're relying on something not available in your version, I just ran it fine on version `11.2.2` ( from `rake --version` )

**Comment by jonasman** [comment]
```
$ rake --version
rake, version 0.9.6
```

Maybe that's why.

**Comment by jonasman** [comment]
anyone i managed to get cocoapods master via `bundle`. So i wont be using this.

**Comment by paulb777** [comment]
Might be nice to update the [docs](https://github.com/CocoaPods/Rainforest) to indicate rake needs to be updated. My year-old Mac had version 0.9.6 installed and it took me awhile to find this bug.
