### ISSUE TITLE
rake bootstrap fails with different errors

### ISSUE THREAD

**Issue by prohoney** [CocoaPods/Rainforest#89]
## First attempt at `rake bootstrap`
The very first I run `rake bootstrap` time I get: 

```
Bootstrapping Cork
rake --no-search bootstrap
/usr/local/bin/bundle

--------------------------------------------------------------------------------
Installing gems
--------------------------------------------------------------------------------

bundle install
Fetching gem metadata from https://rubygems.org/.........
Your bundle is locked to codecov (0.1.14), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of
codecov (0.1.14) has removed it. You'll need to update your bundle to a version other than codecov (0.1.14) that hasn't been removed in order to install.
rake aborted!
Command failed with status (7): [bundle install...]
/Users/prohoney/Dev/learning/r3/Rainforest/Cork/Rakefile:9:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => bootstrap
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake --no-search bootstrap...]
```

I got no other errors. So I changed directory to `/Cork` and ran `bundle update codecov`. 

## Ran `rake bootstrap` again after fixing `Cork`

This time I get a bunch of other errors. 

```
Bootstrapping cocoapods-deintegrate
rake aborted!
Bundler::GemNotFound: Could not find rake-10.4.2 in any of the sources
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
/Library/Ruby/Gems/2.6.0/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
/Users/prohoney/Dev/learning/r3/Rainforest/cocoapods-deintegrate/Rakefile:2:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```
 I get same error for: 

```
Bootstrapping cocoapods-stats
rake aborted!
Bundler::GemNotFound: Could not find rake-10.4.2 in any of the sources
```

When I run `gem list` I get: 

```
rake (12.3.3, 12.3.2, 10.5.0, 10.4.2)
```

Additionally what's odd is that when bootstrapping `cocoapods-docs` **succeeds** with the SAME rake version i.e. I see: 

```
Bootstrapping cocoapods-docs
rake --no-search bootstrap
/usr/local/bin/bundle

--------------------------------------------------------------------------------
Installing gems
--------------------------------------------------------------------------------

bundle install
Fetching gem metadata from http://rubygems.org/.........
Fetching https://github.com/CocoaPods/CLAide.git
Fetching https://github.com/CocoaPods/Core.git
Fetching https://github.com/CocoaPods/CocoaPods.git
Fetching rake 10.4.2
.
.
.
```
I get exact same error for `cocoapods-stats`.
I get exact same error for `CocoaPods` with the only difference that it's expecting that I have rake `10.5.0`

I tried changing directory to each of the above projects and running `bundle install` for them. That only helped me to make `CocoaPods/bin/pod --help` **working**.

## Ran `rake bootstrap` again after running `bundle install` for other gems: 

I got the following errors: 

```
Bootstrapping cocoapods-deintegrate
rake aborted!
Gem::LoadError: You have already activated rake 12.3.3, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this
```
 &&
```
Bootstrapping cocoapods-stats
[!] Some Rake tasks haven been disabled because the environment couldn’t be loaded. Be sure to run `rake bootstrap` first.
```
 &&

```
Bootstrapping CocoaPods
[!] Some Rake tasks haven been disabled because the environment couldn’t be loaded. Be sure to run `rake bootstrap` first or use the VERBOSE environment variable to see errors.
rake --no-search bootstrap
[!] Some Rake tasks haven been disabled because the environment couldn’t be loaded. Be sure to run `rake bootstrap` first or use the VERBOSE environment variable to see errors.
```

I'm learning Ruby, bundler, rbenv, rake as I go along and feel like I'm going in circles for the past few days trying to fix this 😞 

Any thoughts on what to do?

## Setup

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

$ bundle -v
Bundler version 2.2.3 // but I see bundler `Using bundler 1.17.3` and `Using bundler 2.2.3` in the outputs of my `rake bootstrap`

$ gem list
...
bundler (2.2.3, 2.2.2, 2.1.4, 1.17.3, default: 1.17.2)
rake (12.3.3, 12.3.2, 10.5.0, 10.4.2)  
```

**Comment by prohoney** [comment]
FWIW I made an important edit by include the `Gemfile.lock` I get...which is different from the Gemfile.lock available from here https://github.com/CocoaPods/CocoaPods/blob/master/Gemfile.lock

**Comment by dnkoutso** [comment]
@prohoney you dont need to use Rainforest to contribute, just fork https://github.com/CocoaPods/CocoaPods and make a PR from there.

**Comment by prohoney** [comment]
@dnkoutso Thanks. I'm confused. Then why is this page suggesting to use Rainforest? https://guides.cocoapods.org/contributing/dev-environment.html?

**Comment by dnkoutso** [comment]
that probably needs updating to be honest.
